### PR TITLE
Migration scripts for HBase

### PR DESCRIPTION
**Pull request by KulwantSingh011**
The actual scripts for an automated migration of HBase.

### CODE REVIEW

**Review by anoopsjohn — APPROVED** [review]

**Comment by KulwantSingh011** [comment]
# sign-off

**Comment by KulwantSingh011** [comment]
#sign-off

**Comment by sreekzz** [comment]
#sign-off

**Comment by umaanbazhagan** [comment]
Very useful scripts, thank you!

**Comment by gkanade** [comment]
sign off

**Pull request merged**
